<?php
include "header.phtml";
include "session.phtml";


?>
    <!---------- Body starts --------------->
    <p><a href="/MyUser/Logout">Log Out</a></p>
    <h1>Please Create Bank Account</h1>
    <br>
    <form action="/BankAccount/Create" method="post">
        Account Name: <input type="text" name="bankaccountname" placeholder="John's Checking"><br>
        <input type="submit">
    </form>
    <br>
    <a href="/BankAccount/">Back</a>
    <!---------- Body ends -------------------->
<?php
    if ($error) {
        echo "<p class='error'>" . $error . "</p>";
    }
    include "footer.phtml"
?>