<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    <h1>A Legit Bank</h1>
    <br>
    <table>
        <thead>
            <th>Number</th>
            <th>Name</th>
            <th>Balance</th>
        </thead>
        <tbody>
            <?php
                foreach ($bankAccounts as $account) {
                    echo"<tr>";
                    echo "<td><a href='/BankAccount/Single?id='" .$account->getID() . ">". $account->getID() ."</a></td>";
                    echo "<td><a href='/BankAccount/Single?id='" .$account->getID() . ">". $account->getName() ."</a></td>";
                    echo "<td><a href='/BankAccount/Single?id='" .$account->getID() . ">". $account->getBalance() ."</a></td>";
                    echo "</tr>";
                }
            ?>
        </tbody>
    </table>
    <p><a href="/bankaccount/create">Create new account</a></p>
    <br>
<?php echo "<p>$error</p>"; ?>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>