<?php
include "header.phtml";
include "session.phtml";
?>
    <!---------- Body starts --------------->
    <h1>A Legit Bank</h1>
    <br>
    <table>
        <thead>
            <th>Number</th>
            <th>Name</th>
            <th>Balance</th>
        </thead>
        <tbody>
            <?php foreach ($bankAccounts as $account) {
                $link = '/BankAccount/'. $account->getId();
                ?>
                <tr>
                    <td><a href=<?php echo $link . ">".$account->getId() ?> </a></td>
                    <td><a href=<?php echo $link . ">".$account->getName() ?> </a></td>
                    <td><a href=<?php echo $link . ">".$account->getBalance()?> </a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <p><a href="/BankAccount/create">Create new account</a></p>
    <br>
    <!---------- Body ends -------------------->
<?php
    if ($error) {
        echo "<p class='error'>" . $error . "</p>";
    }
    include "footer.phtml"
?>