<?php
include "header.phtml";
include "session.phtml";

//<?php session_name('UserDetails'); session_start(); echo $_SESSION['currentAccount'];
?>

    <!---------- Body starts --------------->
    <p id="logout"><a href="/MyUser/Logout">Log Out</a></p>
    <h1>Edit Bank Account Name:  <?php echo $_SESSION['currentAccountName']?></h1>
    <br>
    <form action="/BankAccount/EditName/<?php echo $_SESSION['currentAccount']?>" method="post">
        Account Name: <input type="text" name="name" placeholder="John's Savings"><br>
        <input type="submit">
    </form>
    <br>
    <a href="/BankAccount/<?php echo $_SESSION['currentAccount']?>">Back</a>
    <!---------- Body ends -------------------->
<?php
    if ($error) {
        echo "<p class='error'>" . $error . "</p>";
    }
    include "footer.phtml"
?>