<?php
include "header.phtml";
include "session.phtml";
?>
    <!---------- Body starts --------------->
    <h1>Please Create Bank Account</h1>
    <br>
    <form action="/BankAccount/Create" method="post">
        Account Name: <input type="text" name="bankaccountname" placeholder="John's Checking"><br>
        <input type="submit">
    </form>
    <br>
    <a href="/BankAccount/">Back</a>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>