<?php
/**
 * Dylan Cross ID 15219491
 * Jordan Felix ID 15152699
 * Thomas Sloman ID 15078758
 */

include "header.phtml";
include "session.phtml";
?>
    <!---------- Body starts --------------->
    <h2>Sign Up:</h2>
    <br>
    <form id="createMyUser" action="/MyUser/Create" method="post">
        First Name: <input class="createaccounttext" type="text" name="fname" placeholder="John"><br>
        Last Name: <input class="createaccounttext" type="text" name="lname" placeholder="Smith"><br>
        Phone Number <input class="createaccounttext" type="tel" name="phone" placeholder="1-888-888-8888"><br>
        Address: <input class="createaccounttext" type="text" name="address" placeholder="123 Massey st, Massey, Auckland, 0614"><br>
        <br><h3>Login Details</h3>
        Email: <input class="createaccounttext" type="email" name="email" placeholder="example@email.com"><br>
        Password: <input class="createaccounttext" type="password" name="password" placeholder="******"><br>
        Confirm Password: <input class="createaccounttext" type="password" name="confirmpassword" placeholder="******"><br>
        <input type="submit">
    </form>
    <br>
    <!---------- Body ends -------------------->
<?php
    if ($error) {
        echo "<p class='error'>" . $error . "</p>";
    }
    include "footer.phtml"
?>