<?php
include "header.phtml";
include "session.phtml";
session_start();
?>
    <!---------- Body starts --------------->
    <h1>A Legit Bank</h1>
    <br>
    <form action="/MyUser/Login" method="post" enctype="multipart/form-data">
        E-mail: <input type="email" name="email"><br>
        Password: <input type="password" name="pw"><br>
        <input type="submit">
    </form>
    <br>
    <a href="/MyUser/Create">Sign Up</a>
    <!---------- Body ends -------------------->
<?php
    if ($error) {
        echo "<p class='error'>" . $error . "</p>";
    }
    include "footer.phtml"
?>