<?php
    include "header.phtml";
    session_start();
?>
    <!---------- Body starts --------------->
    <h1>A Legit Bank</h1>
    <br>
    <form action="/MyUser/Login" method="post" enctype="multipart/form-data">
        E-mail: <input type="email" name="email"><br>
        Password: <input type="password" name="pw"><br>
        <input type="submit">
    </form>
    <br>
    <?php echo "<p>$error</p>"; ?>
    <a href="/MyUser/Create">Sign Up</a>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>