<?php
/**
 * Dylan Cross ID 15219491
 * Jordan Felix ID 15152699
 * Thomas Sloman ID 15078758
 */

include "header.phtml";
include "session.phtml";

if ($_SESSION['sort'] == "amount" && $_SESSION['order'] == "DESC") {
    $amountSort = "/BankAccount/" . $account->getId() . "?sort=amount&order=ASC";
} else {
    $amountSort = "/BankAccount/" . $account->getId() . "?sort=amount&order=DESC";
}

if ($_SESSION['sort'] == "type" && $_SESSION['order'] == "DESC") {
    $typeSort = "/BankAccount/" . $account->getId() . "?sort=type&order=ASC";
} else {
    $typeSort = "/BankAccount/" . $account->getId() . "?sort=type&order=DESC";
}

if ($_SESSION['sort'] == "date" && $_SESSION['order'] == "DESC") {
    $dateSort = "/BankAccount/" . $account->getId() . "?sort=date&order=ASC";
} else {
    $dateSort = "/BankAccount/" . $account->getId() . "?sort=date&order=DESC";
}

?>

<p id="logout"><a href="/MyUser/Logout">Log Out</a></p>
<h2><?php echo $account->getName() . " : $" . $account->getBalance() ?> &nbsp;&nbsp;<a href="/BankAccount/EditName/<?php echo $account->getId()?>">Edit Name</a></h2>
<br>
<h4>Transactions for <?php echo $account->getName() ?></h4>
<table>
    <thead>
        <th><a href="<?php echo $amountSort?>">Amount</a></th>
        <th><a href="<?php echo $typeSort?>">Type</a></th>
        <th><a href="<?php echo $dateSort?>">Date</a></th>
    </thead>
    <tbody>
        <?php foreach ($transactions as $trans) {
            ?>
            <tr>
                <td><?php echo $trans->getAmount() ?></td>
                <td><?php echo $trans->getType() ?></td>
                <td><?php echo $trans->getDate() ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<br>
<h4>Add transaction:</h4>
<form action="/Transaction/Create" method="POST">
    Amount: $<input type="number" name="amount" placeholder="100.00" step="0.01"><br>
    Type:<br>
    &nbsp;<input type="radio" name="type" value="Deposit" checked> Deposit<br>
    &nbsp;<input type="radio" name="type" value="Withdrawal"> Withdrawal<br>
    <input type="submit">
</form>
<br>
<a href="/BankAccount/">Back</a>

<?php
    if ($error) {
       echo "<p class='error'>" . $error . "</p>";
    }
    include "footer.phtml"
?>
