<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    <h1>Please Login</h1>
    <br>
    <form method="post">
        E-mail: <input type="email" name="email"><br>
        Password: <input type="password" pw="password"><br>
        <input type="submit">
    </form>
    <br>
    <a href="/User/create">Sign Up</a>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>